WP-r59070: External Libraries: Skip instanceof check when null in Text_Diff::_check().
On the first `foreach` loop in Text_Diff::_check()`, `$prevtype` is `null`. As `instanceof` requires the class name term to be an object or string, a fatal error is thrown:

>Fatal error: Uncaught Error: Class name must be a valid object or a string on line 279

This change:
* Adds a simple test for the `Text_Diff::_check()` method, which is how the bug was discovered as the test could never pass with the code as-is.

* Adds a defensive guard to protect against the fatal. It checks if `$prevtype` is not `null` as a pre-condition to for checking the instance. This bugfix also resolves the failing test.

Follow-up to https://core.trac.wordpress.org/changeset/49194, https://core.trac.wordpress.org/changeset/7747.

WP:Props jrf, hellofromTonya.
See https://core.trac.wordpress.org/ticket/62083.

---

Merges https://core.trac.wordpress.org/changeset/59070 / WordPress/wordpress-develop@951f887f8a to ClassicPress.