Fix fatal error uploading media on PHP8 (#979)
* WP-r52269: Media: Fix `TypeError` and improve `wp_exif_frac2dec()` to only return `int` or `float`.

For certain images, `wp_exif_frac2dec()` unexpectedly returned a string instead of `int` or `float`. This can occur when an image is missing meta and calls the function with `'0/0'`. For those images, a fatal error was thrown on PHP 8.0+:

{{{
TypeError: round(): Argument https://core.trac.wordpress.org/ticket/1 ($num) must be of type int|float, string given
}}}

Upon deeper review, inconsistent and unexpected results were returned from different types of input values passed to the function.

Changes are:

* Maintains backwards-compatibility for valid input values.
* Fixes handling of invalid input values by bailing out to return the documented type of `int|float` by returning `0`.
* Improves the fractional conditional check.
* Improves the calculated fraction handling to ensure (a) the numerator and denominator are both numeric and (b) the denominator is not equal to zero.
* Safeguards the behavior via tests for all possible ways code could flow through the function.
* Safeguards the backwards-compatibility of the `wp_read_image_metadata()` by adding some defensive coding around the calls to the `wp_exif_frac2dec()` function.

These changes fix the fatal error and make the function more secure, stable, and predictable while maintaining backwards-compatibility for valid input values.

Follow-up to https://core.trac.wordpress.org/changeset/6313, https://core.trac.wordpress.org/changeset/9119, https://core.trac.wordpress.org/changeset/22319, https://core.trac.wordpress.org/changeset/28367, https://core.trac.wordpress.org/changeset/45611, https://core.trac.wordpress.org/changeset/47287.

WP:Props adamsilverstein, jrf, peterwilsoncc, praem90, stevegs, tobiasbg.
Fixes https://core.trac.wordpress.org/ticket/54385.

Conflicts:
- src/wp-admin/includes/image.php
- tests/phpunit/tests/image/meta.php

---

Merges https://core.trac.wordpress.org/changeset/52269 / WordPress/wordpress-develop@8aa625b795 to ClassicPress.

* Fix merge conflicts from backport of 52269

* WP-r52270: Media: Replace `tests/phpunit/data/images/sugar-mountain.jpg` test image.

The test image included in https://core.trac.wordpress.org/changeset/52269 was invalid at 0 bytes. This commit adds the correct test image.

Follow-up https://core.trac.wordpress.org/changeset/52269.

See https://core.trac.wordpress.org/ticket/54385.

---

Merges https://core.trac.wordpress.org/changeset/52270 / WordPress/wordpress-develop@cc17d8c4cb to ClassicPress.

* Fix indentation

* Fix spacing in tests

Co-authored-by: Tonya Mork <hellofromtonya@git.wordpress.org>
Co-authored-by: Laurence Bahiirwa <laurence@mediauganda.com>